#!/usr/bin/env python3
"""Recompose the recovered, computed atlas with vector labels and hull outlines.

No geometry is generated by an image model. Raster geometry comes from Bernat's
public 16 September study; every parameter and overlay is in study.json.
The one PDF contains independently sized poster, atlas and specimen pages.
"""
from pathlib import Path
from fractions import Fraction
import hashlib, json, math, io
import numpy as np
from PIL import Image
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, ConnectionPatch
from matplotlib.backends.backend_pdf import PdfPages
from scipy.spatial import ConvexHull

ROOT = Path(__file__).resolve().parent
PUBLIC = ROOT/'public'
OUT = ROOT/'figures'
OUT.mkdir(exist_ok=True)
STUDY = json.loads((PUBLIC/'data/study.json').read_text())
SAMPLES = STUDY['samples']
INK, MUTED, LINE = '#193345', '#50677a', '#d9e1e6'
RED, BLUE = STUDY['display']['pieceColors']
plt.rcParams.update({'font.family':'DejaVu Sans', 'mathtext.fontset':'stix',
 'pdf.fonttype':42, 'ps.fonttype':42, 'font.size':12, 'text.color':INK,
 'axes.edgecolor':LINE, 'savefig.facecolor':'white'})

def hull(z):
    z=np.asarray(z,dtype=complex)
    if len(z)<3:return z
    a=np.column_stack([z.real,z.imag])
    return z[ConvexHull(a).vertices]

def poly_distance(z,p):
    """Distance from each complex point z to the polygonal curve p."""
    z=np.asarray(z)[:,None];a=np.asarray(p)[None,:];b=np.roll(a,-1,axis=1)
    v=b-a
    t=np.clip(np.real((z-a)*np.conj(v))/np.maximum(abs(v)**2,1e-300),0,1)
    return np.min(abs(z-(a+t*v)),axis=1)

def verify():
    rows=[]
    for s in SAMPLES:
        lm=complex(*s['lambda_minus']);lp=complex(*s['lambda_plus'])
        a,g=s['alpha_display'],s['gamma_display'];rho=s['rho']
        coord=max(abs(lm-np.exp(1j*(a-g))/rho),abs(lp-np.exp(-1j*(a+g))/rho))
        h=np.array([0j])
        for _ in range(s['K']['depth']):h=hull(np.r_[-1+lm*h,1+lp*h])
        recorded=np.array([complex(*p) for p in s['K']['hull']])
        hk=max(poly_distance(recorded,h).max(),poly_distance(h,recorded).max())
        hd=hull((lm*h[:,None]-lp*h[None,:]).ravel())
        rd=np.array([complex(*p) for p in s['D']['hull']])
        dd=max(poly_distance(rd,hd).max(),poly_distance(hd,rd).max())
        r=max(abs(lm),abs(lp));tailK=r**22/(1-r);tailD=(abs(lm)+abs(lp))*tailK
        ferr=max(abs(complex(*s['K']['fixedPoints'][0]['point'])+1/(1-lm)),
                 abs(complex(*s['K']['fixedPoints'][1]['point'])-1/(1-lp)))
        row={'label':s['label'],'coordinate_residual':float(coord),
             'finite_K_hull_boundary_Hausdorff_discrepancy':float(hk),
             'finite_D_hull_boundary_Hausdorff_discrepancy':float(dd),
             'fixed_point_residual':float(ferr),
             'K_tail_bound_exact_arithmetic':float(tailK),
             'D_tail_bound_exact_arithmetic':float(tailD)}
        assert coord<1e-13 and hk<1e-9 and dd<1e-9 and ferr<1e-13,row
        assert abs(s['K']['tailBound']-tailK)<1e-12
        assert abs(s['D']['tailBound']-tailD)<1e-12
        rows.append(row)
    (OUT/'Mathematical_Overlay_QA.json').write_text(json.dumps({'status':'passed',
        'scope':'Independent floating-point reconstruction of depth-22 convex hulls, coefficients and branch fixed points; not an interval certificate.',
        'results':rows},indent=2)+'\n')

def frac(x):
    q=Fraction(x).limit_denominator(300)
    return str(q.numerator) if q.denominator==1 else rf'\frac{{{q.numerator}}}{{{q.denominator}}}'

def colour(s):return tuple(s['rgb'])

def specimen(fig,s,kind,rect,fs=14,hullwidth=.75):
    ax=fig.add_axes(rect)
    b=s[kind]['bounds'];img=Image.open(PUBLIC/s['images'][kind])
    ax.imshow(img,extent=b,origin='upper',interpolation='none',zorder=1)
    hp=np.asarray(s[kind]['hull']);closed=np.vstack([hp,hp[0]])
    ax.plot(closed[:,0],closed[:,1],color='#728792',lw=hullwidth,alpha=.85,zorder=3)
    if kind=='K':
        for i,fp in enumerate(s['K']['fixedPoints']):
            x,y=fp['point'];ax.plot(x,y,'o',ms=fs*.20,mfc='white',mec=[RED,BLUE][i],mew=.65,zorder=5)
    else:
        ax.plot(2,0,'o',ms=fs*.26,mfc='white',mec=INK,mew=.7,zorder=5)
        ax.annotate('$2$',(2,0),xytext=(-5,6),ha='right',textcoords='offset points',fontsize=fs*.82,zorder=6,
                    bbox={'facecolor':'white','edgecolor':'none','alpha':.82,'pad':.05})
    xmin,xmax,ymin,ymax=b;scale=xmax-xmin
    sx=xmin+.11*scale;sy=ymin+.08*scale
    ax.plot([sx,sx+1],[sy,sy],color=MUTED,lw=.75,zorder=5)
    ax.text(sx+.5,sy-.035*scale,'1',ha='center',va='top',fontsize=fs*.58,color=MUTED)
    ax.set_xlim(xmin,xmax);ax.set_ylim(ymin,ymax);ax.set_aspect('equal');ax.axis('off')
    return ax

def torus(fig,rect,fs=16):
    ax=fig.add_axes(rect)
    ax.imshow(Image.open(PUBLIC/'assets/atlas-overview-6k.png'),extent=[0,1,0,1],aspect='auto',interpolation='none')
    ax.axis('off')
    for s in SAMPLES:
        x,y=s['screen_uv'];y=1-y
        ax.text(x,y,s['label'],ha='center',va='center',fontsize=fs,weight='bold',color=colour(s),
                bbox={'boxstyle':'circle,pad=.18','facecolor':'white','edgecolor':INK,'linewidth':.65},zorder=10)
    return ax

def density_key(fig,rect,fs=12):
    ax=fig.add_axes(rect);d=STUDY['display']['differenceDensity']
    u=np.linspace(0,1,512);arr=np.ones((12,len(u),4));arr[:,:,:3]=matplotlib.colors.to_rgb(MUTED);arr[:,:,3]=u
    ax.imshow(arr,extent=[0,1,0,1],aspect='auto',origin='lower');ax.axis('off')
    for t in [0,.005,.02,.1,d['density_ref']]:
        x=np.log1p(t/d['softening'])/np.log1p(d['density_ref']/d['softening'])
        label='0' if t==0 else ('$\\geq0.475$' if t==d['density_ref'] else f'{t:g}')
        ax.text(x,-.35,label,ha='center',va='top',fontsize=fs,color=MUTED)

def poster():
    fig=plt.figure(figsize=(61/2.54,43/2.54))
    fig.text(.5,.971,'Attractors and contact differences in a four-dimensional atlas',ha='center',fontsize=30,weight='bold')
    fig.text(.5,.938,r'Direct/direct similarities  ·  Equal contractions $w=1/2$  ·  Six linked parameters',ha='center',fontsize=20,color=MUTED)
    maprect=[.262,.368,.476,.476*(61/43)*.75]
    axmap=torus(fig,maprect,fs=19)
    cards={}
    for i,s in enumerate(SAMPLES):
        col=i%2;row=i//2;x=.014 if col==0 else .755;y=.663-row*.287;w=.231;h=.254
        cards[s['label']]=(x,y,w,h)
        fig.add_artist(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=.005,rounding_size=.004',
            transform=fig.transFigure,facecolor='white',edgecolor=LINE,linewidth=1,zorder=-10))
        fig.text(x+.012,y+h-.027,s['label'],fontsize=24,weight='bold',color=colour(s))
        fig.text(x+.046,y+h-.024,rf'$\rho\approx {s["rho"]:.6f}$',fontsize=19)
        fig.text(x+.012,y+h-.064,rf'$\alpha/\pi={frac(s["alpha_pi"])}\qquad\gamma/\pi={frac(s["gamma_pi"])}$',fontsize=19,color=MUTED)
        fig.text(x+.063,y+.153,r'$K_p$',ha='center',fontsize=21)
        fig.text(x+.174,y+.153,r'$D_p$',ha='center',fontsize=21)
        imgw=.104;imgh=imgw*61/43
        specimen(fig,s,'K',[x+.005,y+.004,imgw,imgh],fs=17)
        specimen(fig,s,'D',[x+.119,y+.004,imgw,imgh],fs=17)
        uv=s['screen_uv'];pin=(uv[0],1-uv[1])
        fx=maprect[0]+uv[0]*maprect[2];fy=maprect[1]+(1-uv[1])*maprect[3]
        elbowx=.251 if col==0 else .749;targetx=x+w if col==0 else x
        targety=y+.19
        startx=fx+(-.007 if col==0 else .007)
        fig.add_artist(plt.Line2D([startx,elbowx,elbowx,targetx],[fy,fy,targety,targety],
            transform=fig.transFigure,color=colour(s),lw=.85,alpha=.57,zorder=2))
    fig.text(.5,.343,r'$f_{-,p}(z)=-1+\lambda_-z,\qquad f_{+,p}(z)=1+\lambda_+z$',ha='center',fontsize=23)
    fig.text(.5,.307,r'$\lambda_-=\rho^{-1}e^{i(\alpha-\gamma)},\qquad\lambda_+=\rho^{-1}e^{-i(\alpha+\gamma)}$',ha='center',fontsize=22)
    fig.text(.5,.261,r'$D_p=\lambda_-K_p-\lambda_+K_p$',ha='center',fontsize=25)
    fig.text(.5,.223,r'$K_p\ \mathrm{connected}\quad\Longleftrightarrow\quad 2\in D_p$',ha='center',fontsize=24)
    fig.text(.402,.182,r'$f_{-,p}(K_p)$',ha='center',fontsize=19,color=RED)
    fig.text(.598,.182,r'$f_{+,p}(K_p)$',ha='center',fontsize=19,color=BLUE)
    fig.text(.5,.145,r'$D_p$: shared finite probability-density scale',ha='center',fontsize=16,color=MUTED)
    density_key(fig,[.348,.121,.304,.008],fs=12)
    fig.text(.5,.080,'Gray: finite convex hulls. Rings: branch fixed points. Scale bars: one complex-plane unit.',ha='center',fontsize=14,color=MUTED)
    fig.text(.5,.052,'Finite numerical atlas: hue records a selected pair-address code. Each attractor uses all length-22 words.',ha='center',fontsize=14,color=MUTED)
    fig.text(.5,.028,'The torus is an angular display; its central hole is imposed by the projection. Exact contact is not certified by these samples.',ha='center',fontsize=13,color=MUTED)
    return fig

def paper_atlas():
    fig=plt.figure(figsize=(17/2.54,13/2.54))
    torus(fig,[.01,.015,.98,.98*(17/13)*.75],fs=9)
    return fig

def paper_specimens():
    fig=plt.figure(figsize=(17/2.54,15/2.54))
    for i,s in enumerate(SAMPLES):
        col=i%3;row=i//3;x=.01+col*.332;y=.545-row*.43
        fig.text(x+.012,y+.386,s['label'],fontsize=11,weight='bold',color=colour(s))
        fig.text(x+.073,y+.387,rf'$\rho\approx {s["rho"]:.6f}$',fontsize=9)
        fig.text(x+.075,y+.327,r'$K_p$',ha='center',fontsize=10)
        fig.text(x+.248,y+.327,r'$D_p$',ha='center',fontsize=10)
        iw=.16;ih=iw*17/15
        specimen(fig,s,'K',[x,y+.12,iw,ih],fs=10,hullwidth=.38)
        specimen(fig,s,'D',[x+.166,y+.12,iw,ih],fs=10,hullwidth=.38)
        fig.text(x+.166,y+.065,rf'$\alpha/\pi={frac(s["alpha_pi"])}\quad\gamma/\pi={frac(s["gamma_pi"])}$',fontsize=9,ha='center',color=MUTED)
    fig.text(.5,.074,'Finite convex hulls in gray; branch fixed points ringed; scale bars: one unit.',ha='center',fontsize=7,color=MUTED)
    density_key(fig,[.22,.048,.56,.009],fs=6.7)
    fig.text(.5,.012,'Shared finite probability density (per square complex-plane unit)',ha='center',fontsize=7,color=MUTED)
    return fig

def main():
    verify()
    makers=[('Atlas_4D_Poster_Plate',poster,240),('Atlas_4D_Paper_Atlas',paper_atlas,600),('Atlas_4D_Paper_Specimens',paper_specimens,600)]
    output=OUT/'Atlas_4D_Scientific_Plates.pdf'
    pdf_buffer=io.BytesIO()
    with PdfPages(pdf_buffer,metadata={'Title':'Attractors and contact differences in the 4D atlas','Author':'Bernat Espigulé','Subject':'Poster and manuscript scientific plates; source study 16 September 2026'}) as pdf:
        for name,maker,dpi in makers:
            fig=maker();pdf.savefig(fig,dpi=dpi)
            fig.savefig(OUT/(name+'.png'),dpi=dpi)
            fig.savefig(OUT/(name+'_preview.png'),dpi=75 if name.endswith('Plate') else 150)
            plt.close(fig)
    output.write_bytes(pdf_buffer.getvalue())
    files=[]
    for p in sorted(OUT.iterdir()):
        if p.is_file() and p.name!='RENDER_MANIFEST.json':files.append({'name':p.name,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
    (OUT/'RENDER_MANIFEST.json').write_text(json.dumps({'pdf_pages':[{'page':1,'width_cm':61,'height_cm':43,'use':'poster'},{'page':2,'width_cm':17,'height_cm':13,'use':'manuscript atlas'},{'page':3,'width_cm':17,'height_cm':15,'use':'manuscript specimens'}],'files':files},indent=2)+'\n')
    print(json.dumps({'output':str(output),'files':len(files)},indent=2))

if __name__=='__main__':main()
